name: proceso_cobro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    

  sqflite: ^2.2.2
  esc_pos_utils: ^1.1.0
  esc_pos_bluetooth: ^0.4.1
  oktoast: ^3.3.1
  permission_handler: ^10.2.0
  path: ^1.8.2
  path_provider: ^2.0.11
  http: ^0.13.5
  get: ^4.6.5
  auto_size_text: ^3.0.0
  #ANIMACION LOGIN
  awesome_snackbar_content: ^0.1.2
  #Icons Style
  eva_icons_flutter: ^3.1.0
  #chance icon
  flutter_launcher_icons: ^0.11.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  google_fonts: ^4.0.3
  math_expressions: ^2.3.1


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter_native_splash: 
  image: assets/logo.png
  color: "#ffffff"

  flutter_lints: ^2.0.0


#chance icon laounch
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
#the run: flutter pub run flutter_launcher_icons

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/images/
 
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets\fonts\Quicksand\static\Quicksand-SemiBold.ttf
 